- name: Ensuring chrony is installed
  ansible.builtin.yum:
    name: chrony
    state: installed
  tags:
    - chrony

- name: Configuring chrony
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    mode: 0644
  notify:
    - restart_chronyd
  tags:
    - chrony

- name: Ensuring chronyd is started and enabled
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: True
  tags:
    - chrony

- name: IPv4 Firewall rules for ntpd host
  ansible.builtin.template:
    src: iptables-service-ntpd.j2
    dest: /etc/sysconfig/iptables.d/01-input-service-policy-ntpd
    mode: 0644
  when: ntp_host
  notify:
    - rebuild_iptables
    
