- name: Ensuring ansible can create local facts
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Ensuring we have a place to store centos infra scripts
  file:
    path: /usr/libexec/centos
    state: directory

- name: UTC everywhere
  timezone:
    name: UTC
  tags:
    - tz

- name: Adding admin group
  group:
    name: admins
    state: present

- name: Adding admin user[s]
  user: 
    name: "{{ item.login_name }}" 
    state: present 
    comment: "{{ item.full_name }}" 
    shell: /bin/bash
    append: yes
    groups: admins
  with_items: "{{ admins_list }}"
  when: admins_list is defined
  loop_control:
    label: "{{ item.login_name }}"
  tags:
    - users
- name: Importing admin user[s] ssh pub keys
  authorized_key: 
    user: "{{ item.0.login_name }}" 
    key: "{{ item.1 }}"
  with_subelements:
   - "{{ admins_list }}"
   - ssh_pub_key
  when: admins_list is defined
  loop_control:
    label: "{{ item.0.login_name }}"
  tags:
    - users

- name: Giving sudo access for admin users when needed
  template: 
    src: templates/sudofile.j2 
    dest: /etc/sudoers.d/{{ item.login_name }} 
    mode: 0440 
    owner: root 
    group: root
  with_items: "{{ admins_list }}"
  loop_control:
    label: "{{ item.login_name }}"
  when: admins_list is defined and item.sudo_right
  tags:
    - users

- name: Adding CentOS Infra key
  copy: 
    src: files/RPM-GPG-KEY-CentOS-Infra 
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-Infra
  tags:
    - yum

- name: Configuring CentOS Infra admin repo
  template: 
    src: centos-admin.repo.j2 
    dest: /etc/yum.repos.d/centos-admin.repo
  tags:
    - yum

- name: Creating selinux custom policy drop folder
  file: 
    path: /etc/selinux/centos 
    state: directory 
    owner: root 
    group: root 
    mode: 0750

- name: Ensuring some default packages are installed
  yum: name={{ item }} state=installed
  with_items:
    - screen
    - libsemanage-python
    - nfs-utils
    - rsync
    - bridge-utils
    - smartmontools

- name: Customizing motd
  template: 
    src: motd.j2 
    dest: /etc/motd 
    owner: root 
    group: root 
    mode: 644
  tags:
    - motd

- name: Ensuring tuned is installed
  yum:
    name: tuned
    state: installed
  tags:
    - tuned
- name: Ensuring tuned is started
  service:
    name: tuned
    state: started
    enabled: True
  tags:
    - tuned

- name: Ensuring correct tuned profile is configured
  template:
    src: tuned_active_profile.j2
    dest: /etc/tuned/active_profile
  register: tuned_setting_7
  when: ansible_distribution_major_version == "7" 
  tags:
    - tuned

- name: Ensuring correct tuned profile is configured (el6 version)
  template:
    src: tuned_active_profile.j2
    dest: /etc/tune-profiles/active_profile
  register: tuned_setting_6
  when: ansible_distribution_major_version == "6"
  tags:
    - tuned

- name: Reloading tuned profile if needed
  shell: "tuned-adm profile {{ tuned_profile }}"
  when: tuned_setting_6 is changed or tuned_setting_7 is changed
  tags:
    - tuned

- import_role:
    name: iptables

- import_role:
    name: zabbix-agent
  tags:
    - monitoring

- import_role:
    name: sshd

- name: Adding additional users
  user: 
    name: "{{ item.login_name }}"
    state: present 
    comment: "{{ item.full_name }}" 
    shell: /bin/bash
  with_items: "{{ local_users_list }}"
  loop_control:
    label: "{{ item.login_name }}"
  when: local_users_list is defined
  
- name: Importing local users ssh pub keys
  authorized_key: 
    user: "{{ item.0.login_name }}"
    key: "{{ item.1 }}"
  with_subelements: 
    - "{{ local_users_list }}"
    - ssh_pub_key
  loop_control:
    label: "{{ item.0.login_name }}"
  when: local_users_list is defined

- name: Giving sudo access when needed 
  template:  
    src: templates/sudofile.j2 
    dest: /etc/sudoers.d/'{{ item.login_name }}' 
    mode: 0440 
    owner: root 
    group: root
  with_items: '{{ local_users_list }}'
  when: 
    - local_users_list is defined
    - item.sudo_right 
  loop_control:
    label: "{{ item.login_name }}"
 
- include_tasks: os_updates.yml
