- block:
    - name: Ensuring we have correct dnf versionlock plugin
      ansible.builtin.yum:
        name: python3-dnf-plugin-versionlock
        state: installed
    - name: Pin pkgs to specific version (if needed)
      ansible.builtin.template:
        src: dnf-versionlock.list.j2
        dest: /etc/dnf/plugins/versionlock.list
  when:
    - ansible_distribution_major_version == '8'
  tags:
    - dnf

- name: Adding the centos-updates yum script
  ansible.builtin.template:
    src: centos-updates.j2
    dest: /usr/libexec/centos/centos-updates
    mode: 0750
    owner: root
    group: root
  tags:
    - updates

- name: Adding yum daily autoupdate
  ansible.builtin.cron:
    name: "Yum daily update"
    job: "/usr/libexec/centos/centos-updates"
    user: root
    state: present
    weekday: "1,2,3,4"
    hour: "9"
    minute: "0"

