- name: Adding the centos-updates yum script
  ansible.builtin.template:
    src: centos-updates.j2
    dest: /usr/libexec/centos/centos-updates
    mode: 0750
    owner: root
    group: root
  tags:
    - updates

- name: Adding yum daily autoupdate
  ansible.builtin.cron:
    name: "Yum daily update"
    job: "/usr/libexec/centos/centos-updates"
    user: root
    state: present
    weekday: "1,2,3,4"
    hour: "9"
    minute: "0"

- name: Cleaning-up some older scripts from puppet
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /usr/local/bin/centos-updates
